const questions=[
{id:1,text:"¿Cuál es el objetivo principal de este curso?",options:["Aprender los conceptos fundamentales","Completar actividades sin estudiar","Evitar el uso de recursos digitales","Ninguna de las anteriores"]},
{id:2,text:"¿Cuál de las siguientes opciones corresponde a un ejemplo de aprendizaje activo?",options:["Resolver un caso práctico","No participar en clase","Ignorar las actividades","Copiar respuestas"]},
{id:3,text:"Pregunta de ejemplo 3: reemplaza este contenido por una pregunta de tu curso.",options:["Opción A","Opción B","Opción C","Opción D"]}
];
let currentQuestion=0;const answers={};let remainingSeconds=30*60;let examStarted=false;
const questionText=document.getElementById("questionText"),answersContainer=document.getElementById("answers"),questionCounter=document.getElementById("questionCounter"),questionNav=document.getElementById("questionNav"),prevBtn=document.getElementById("prevBtn"),nextBtn=document.getElementById("nextBtn"),finishBtn=document.getElementById("finishBtn"),timer=document.getElementById("timer");
function renderNavigation(){questionNav.innerHTML="";questions.forEach((q,i)=>{const b=document.createElement("button");b.textContent=i+1;b.className="question-number";if(i===currentQuestion)b.classList.add("active");if(answers[q.id]!==undefined)b.classList.add("answered");b.onclick=()=>{if(!examStarted)return;currentQuestion=i;renderQuestion()};questionNav.appendChild(b)})}
function renderQuestion(){const q=questions[currentQuestion];questionCounter.textContent=`Pregunta ${currentQuestion+1} de ${questions.length}`;questionText.textContent=q.text;answersContainer.innerHTML="";q.options.forEach((o,oi)=>{const l=document.createElement("label");l.className="answer-option"+(answers[q.id]===oi?" selected":"");const input=document.createElement("input");input.type="radio";input.name="answer";input.checked=answers[q.id]===oi;input.onchange=()=>{answers[q.id]=oi;renderQuestion()};const s=document.createElement("span");s.textContent=o;l.append(input,s);answersContainer.appendChild(l)});prevBtn.disabled=currentQuestion===0;nextBtn.disabled=currentQuestion===questions.length-1;renderNavigation()}
prevBtn.onclick=()=>{if(currentQuestion>0){currentQuestion--;renderQuestion()}};nextBtn.onclick=()=>{if(currentQuestion<questions.length-1){currentQuestion++;renderQuestion()}};
finishBtn.onclick=()=>{const answered=Object.keys(answers).length;if(!confirm(`Has respondido ${answered} de ${questions.length} preguntas.\n\n¿Deseas finalizar la evaluación?`))return;window.examFinished=true;console.log({answers,incidents:window.proctoringIncidents||[]});alert("Evaluación finalizada. En la siguiente etapa enviaremos respuestas e incidencias al servidor.")};
function updateTimer(){const m=Math.floor(remainingSeconds/60),s=remainingSeconds%60;timer.textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`;if(!examStarted)return;if(remainingSeconds<=0){clearInterval(timerInterval);window.examFinished=true;alert("El tiempo ha finalizado.");return}remainingSeconds--}
const timerInterval=setInterval(updateTimer,1000);window.startExamClock=()=>{examStarted=true};renderQuestion();updateTimer();
