window.proctoringIncidents=[];window.examFinished=false;
const consentCheck=document.getElementById("consentCheck"),startExamBtn=document.getElementById("startExamBtn"),startOverlay=document.getElementById("startOverlay"),securityOverlay=document.getElementById("securityOverlay"),cameraPreview=document.getElementById("cameraPreview"),cameraDot=document.getElementById("cameraDot"),cameraStatus=document.getElementById("cameraStatus"),incidentCount=document.getElementById("incidentCount"),securityBadge=document.getElementById("securityBadge"),startError=document.getElementById("startError"),toast=document.getElementById("toast");
let monitoringActive=false,cameraStream=null,lastIncident={};
consentCheck.onchange=()=>startExamBtn.disabled=!consentCheck.checked;
function showToast(m){toast.textContent=m;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}
function registerIncident(type,details=""){if(!monitoringActive||window.examFinished)return;const now=Date.now();if(lastIncident[type]&&now-lastIncident[type]<1200)return;lastIncident[type]=now;const ev={type,details,time:new Date().toISOString()};window.proctoringIncidents.push(ev);incidentCount.textContent=window.proctoringIncidents.length;const c=window.proctoringIncidents.length;if(c>=6){securityBadge.textContent="Revisar";securityBadge.className="badge danger"}else if(c>=2){securityBadge.textContent="Atención";securityBadge.className="badge warning"}console.warn("[PROCTORING]",ev);showToast("Incidencia registrada: "+type)}
async function startCamera(){if(!navigator.mediaDevices?.getUserMedia)throw new Error("Sin cámara");cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:480}},audio:false});cameraPreview.srcObject=cameraStream;cameraDot.className="dot on";cameraStatus.textContent="Cámara activa";cameraStream.getVideoTracks().forEach(t=>t.addEventListener("ended",()=>{cameraDot.className="dot off";cameraStatus.textContent="Cámara desconectada";registerIncident("CÁMARA INTERRUMPIDA")}))}
async function requestFullscreen(){if(!document.fullscreenElement&&document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen()}
startExamBtn.onclick=async()=>{startExamBtn.disabled=true;startError.textContent="";try{await startCamera();await requestFullscreen();monitoringActive=true;startOverlay.classList.add("hidden");window.startExamClock?.()}catch(e){startError.textContent="No se pudo iniciar. Verifica el permiso de cámara y vuelve a intentarlo.";startExamBtn.disabled=false;console.error(e)}};
document.addEventListener("contextmenu",e=>{if(!monitoringActive)return;e.preventDefault();registerIncident("MENÚ CONTEXTUAL BLOQUEADO")});
["copy","cut","paste"].forEach(n=>document.addEventListener(n,e=>{if(!monitoringActive)return;e.preventDefault();registerIncident(n.toUpperCase()+" BLOQUEADO")}));
document.addEventListener("keydown",e=>{if(!monitoringActive)return;const k=e.key.toLowerCase(),ctrl=e.ctrlKey||e.metaKey;if((ctrl&&["c","x","v","p","s","u"].includes(k))||e.key==="F12"){e.preventDefault();e.stopPropagation();registerIncident("ATAJO BLOQUEADO",`${e.ctrlKey?"Ctrl+":""}${e.key}`)}});
document.addEventListener("visibilitychange",()=>{if(!monitoringActive||window.examFinished)return;if(document.hidden){registerIncident("CAMBIO DE PESTAÑA / VENTANA OCULTA");securityOverlay.classList.remove("hidden")}else securityOverlay.classList.add("hidden")});
window.addEventListener("blur",()=>{if(monitoringActive&&!window.examFinished)registerIncident("VENTANA SIN FOCO")});
document.addEventListener("fullscreenchange",()=>{if(monitoringActive&&!window.examFinished&&!document.fullscreenElement){registerIncident("SALIDA DE PANTALLA COMPLETA");showToast("Debes permanecer en pantalla completa")}});
window.addEventListener("beforeunload",e=>{if(!monitoringActive||window.examFinished)return;e.preventDefault();e.returnValue=""});
